name: Build Desktop App

on:
  workflow_dispatch: # 允许我们在网页上手动点击按钮触发打包

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Nativefier
      run: npm install -g nativefier

    - name: Run Nativefier Packager
      run: |
        nativefier --name "灵动提醒" "index.html" --internal-urls ".*" --width 880 --height 750 --platform windows

    - name: Zip the Output App
      run: |
        Compress-Archive -Path "灵动提醒-win32-x64" -DestinationPath "灵动提醒-桌面绿色版.zip"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 灵动提醒-Windows版
        path: 灵动提醒-桌面绿色版.zip
